# Generated by Django 3.2.9 on 2022-04-21 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('w3', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountmetamask',
            name='balance',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='accountmetamask',
            name='count_trans',
            field=models.IntegerField(default=0),
        ),
    ]
