# Generated by Django 3.2.9 on 2022-04-21 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('w3', '0002_auto_20220421_1711'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountmetamask',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
