# Generated by Django 3.2.9 on 2022-05-01 14:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('w3', '0003_accountmetamask_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('to_account', models.CharField(max_length=250)),
                ('gas', models.IntegerField(default=0)),
                ('value', models.FloatField(default=0)),
                ('gas_price', models.IntegerField(default=0)),
                ('res_hash', models.CharField(max_length=250)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='w3.accountmetamask')),
            ],
        ),
    ]
