# Generated by Django 3.2.9 on 2022-05-12 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('w3', '0005_alter_transaction_res_hash'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='data',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
