# Generated by Django 3.2.9 on 2022-05-13 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('w3', '0006_transaction_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='text',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
