# Generated by Django 3.2.9 on 2022-06-02 16:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('w3', '0010_ipfs_result_hash'),
    ]

    operations = [
        migrations.AddField(
            model_name='ipfs',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='w3.accountmetamask'),
        ),
        migrations.AddField(
            model_name='ipfs',
            name='data',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='ipfs',
            name='gas',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ipfs',
            name='gas_price',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ipfs',
            name='res_hash',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='ipfs',
            name='text',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='ipfs',
            name='to_account',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
