# Generated by Django 3.2.9 on 2022-06-02 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('w3', '0011_auto_20220602_1641'),
    ]

    operations = [
        migrations.AddField(
            model_name='ipfs',
            name='hash_ipfs',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
