# Generated by Django 3.2.9 on 2022-06-02 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('w3', '0013_remove_ipfs_res_hash'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ipfs',
            name='data',
        ),
    ]
