# Generated by Django 3.2.9 on 2022-06-06 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('w3', '0014_remove_ipfs_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ipfs',
            name='file',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
