# Generated by Django 3.2.9 on 2022-07-28 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('w3', '0018_alter_accountmetamask_private_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accountmetamask',
            name='private_key',
        ),
    ]
