# Generated by Django 3.2.9 on 2022-09-14 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('w3', '0018_auto_20220912_1840'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='text',
        ),
    ]
