# Generated by Django 3.2.9 on 2022-08-09 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('w3', '0019_remove_accountmetamask_private_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='data',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
    ]
