# Generated by Django 3.2.9 on 2022-10-18 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('w3', '0019_remove_transaction_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='gas',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='gas_price',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='to_account',
        ),
    ]
