# Generated by Django 3.2.9 on 2022-08-09 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('w3', '0020_alter_transaction_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='data',
            field=models.CharField(blank=True, max_length=50000, null=True),
        ),
    ]
