# Generated by Django 3.2.9 on 2022-06-21 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='metamask_to',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
