# Generated by Django 3.2.9 on 2022-07-02 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0002_alter_message_metamask_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='show',
            field=models.BooleanField(default=False),
        ),
    ]
