# Generated by Django 3.2.9 on 2021-12-09 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20211129_1753'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Author',
        ),
    ]
