# Generated by Django 3.2.8 on 2021-10-12 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gadget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('category', models.CharField(max_length=250)),
                ('content', models.TextField()),
                ('author', models.CharField(max_length=250)),
                ('datetime', models.DateTimeField(verbose_name='Дата публикации')),
            ],
        ),
    ]
