# Generated by Django 3.2.9 on 2021-11-27 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('image', models.ImageField(max_length=250, upload_to='')),
                ('content', models.TextField()),
                ('link', models.URLField(max_length=1000)),
                ('datetime', models.DateTimeField(verbose_name='Дата публикации')),
                ('author', models.ManyToManyField(to='users.Author')),
                ('language', models.ManyToManyField(to='blog.Language')),
            ],
        ),
        migrations.DeleteModel(
            name='Gadget',
        ),
    ]
