# Generated by Django 3.2.9 on 2021-11-29 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20211127_1821'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='posts',
            options={'ordering': ['datetime']},
        ),
        migrations.AddField(
            model_name='posts',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True, default=None, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='posts',
            name='datetime',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
