# Generated by Django 3.2.9 on 2021-12-17 17:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20211217_1732'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posts',
            name='language',
        ),
        migrations.AddField(
            model_name='posts',
            name='language',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='blog.language'),
            preserve_default=False,
        ),
    ]
