# Generated by Django 3.2.9 on 2021-12-21 07:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0006_auto_20211217_1749'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='image',
            field=models.ImageField(default=1, max_length=250, upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='posts',
            name='link',
            field=models.URLField(default=1, max_length=1000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='posts',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
