# Generated by Django 3.2.9 on 2021-12-29 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_alter_posts_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndexInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=250)),
                ('facebook', models.CharField(max_length=250)),
                ('instagram', models.CharField(max_length=250)),
            ],
        ),
    ]
