# Generated by Django 3.2.9 on 2022-01-17 07:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_indexinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='update_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, null=True),
        ),
    ]
