# Generated by Django 3.2.9 on 2022-01-21 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_posts_update_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='visible',
            field=models.BooleanField(default=True),
        ),
    ]
