# Generated by Django 3.2.9 on 2022-09-06 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_kurs'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kurs',
            old_name='sale',
            new_name='EUR',
        ),
        migrations.RenameField(
            model_name='kurs',
            old_name='buy',
            new_name='USD',
        ),
        migrations.RemoveField(
            model_name='kurs',
            name='name',
        ),
    ]
